---                                                                                                                                  
kind: pipeline
type: docker
name: default

steps:
  - name: syntax check
    failure: ignore
    image: geerlingguy/docker-ubuntu1804-ansible:testing
    commands:
      - "find . -name '*.yml' | sort | grep -v '.drone.yml' | xargs ansible-playbook --syntax-check --list-tasks"
  - name: ansible lint
    image: geerlingguy/docker-ubuntu1804-ansible:testing
    commands:
      - "find . -name '*.yml' | sort | grep -v '.drone.yml' | xargs ansible-lint"
