---                                                                                                                                  
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: testing the exec runner
    commands:
    - echo "yay i'm working!"

  - name: verify that kubectl is in the path
    commands:
    - which kubectl

  - name: verify that kind is in the path
    commands:
    - which kind

  - name: delete cluster and run script
    commands:
    - kind delete cluster

  - name: create the default kind cluster
    commands:
    - kind create cluster

  - name: verify kubectl can talk to kind
    commands:
    - kubectl cluster-info --context kind-kind
 
  - name: install tekton in kind
    commands:
    - kubectl apply --filename "https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml"

  - name: delete the cluster
    commands:
    - kind delete cluster

  - name: email on success
    commands:
      - bash -x email-success.sh ${DRONE_COMMIT} ${DRONE_COMMIT_BRANCH} ${DRONE_COMMIT_AUTHOR} ${DRONE_REPO_OWNER} ${DRONE_REPO_NAME} ${DRONE_COMMIT_AUTHOR_EMAIL} ${DRONE_BUILD_NUMBER} ${DRONE_REPO_LINK}
    when:
      status:
      - success

  - name: email on failure
    commands:
      - bash -x email-failure.sh ${DRONE_COMMIT} ${DRONE_COMMIT_BRANCH} ${DRONE_COMMIT_AUTHOR} ${DRONE_REPO_OWNER} ${DRONE_REPO_NAME} ${DRONE_COMMIT_AUTHOR_EMAIL} ${DRONE_BUILD_NUMBER} ${DRONE_REPO_LINK}
    when:
      status:
      - failure 
